# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env:
      APP_NAME: "UCOL_salinity_exp1.Rdata"
      APP_DIR: ""
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSCONNECT_URL: ${{ secrets.SHINYAPPS_ACCOUNT }}
      RSCONNECT_APIKEY: ${{ secrets.RSCONNECT_APIKEY }}
    strategy:
      matrix:
        r-version: ['4.1.1']
    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install dependencies
        run: |
          if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')
          renv::restore()
          renv::snapshot()
        shell: Rscript {0}
        
      - name: Install Rconnect
        run: install.packages("rsconnect")
        shell: Rscript {0}
        
      # - name: Check
        #run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        #shell: Rscript {0}
        
      - name: Generate manifest.json
        run: |
          rsconnect::writeManifest(appDir = "${{ env.APP_DIR }}")
        shell: Rscript {0}
        
